name = "Bloons TD6"
home = "https://discord.com/channels/731205301247803413/1188559959508668527"
default_url = "https://github.com/Matt41321/Archipelago/releases/download/v{{version}}/bloonstd6.apworld"
# This used to be broken however it's a lot better now with 100% fuzzer rate

[versions]
"0.7.0" = {}
