name = "melee"
display_name = "Super Smash Bros. Melee"
home = "https://discord.com/channels/731205301247803413/1517571334551371856/1519166710467530863"
default_url = "https://github.com/PinkSwitch/Archipelago/releases/download/{{version}}/melee.apworld"

[versions]
"2.0.1" = {}
