name = "NSMBW"
display_name = "New Super Mario Bros. Wii"
home = "https://discord.com/channels/731205301247803413/1327187652864380948"
default_url = "https://github.com/Miiroun/Archipelago-NewSuperMarioBrosWii/releases/download/V{{version}}/nsmbw.apworld"

[versions]
"0.2.2" = {}
