name = "Super Mario Odyssey"
home = "https://discord.com/channels/1345801058609270794/1353473581513969756"
default_url = "https://github.com/AdalynBlack/SuperMarioOdysseyArchipelago/releases/download/v{{version}}/smo.apworld"
disabled = true

[versions]
"1.7.4" = {}
"1.7.5P1" = { url = "https://github.com/AdalynBlack/SuperMarioOdysseyArchipelago/releases/download/v1.7.5-Pre1/smo.apworld" }
